package visuals;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Ricardo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle("Menu Principal");
        setSize(740, 540);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    private void cargarPanel(JPanel panel) {
        panelCentral.removeAll();
        panelCentral.add(panel);
        panelCentral.revalidate();
        panelCentral.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestion = new javax.swing.JMenu();
        jGestionEstudiantes = new javax.swing.JMenuItem();
        jGestionTutores = new javax.swing.JMenuItem();
        jGestionMaterias = new javax.swing.JMenuItem();
        jMenuTutorias = new javax.swing.JMenu();
        jMenuMaterias = new javax.swing.JMenu();
        jMenuSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jMenuGestion.setText("Gestion");
        jMenuGestion.addActionListener(this::jMenuGestionActionPerformed);

        jGestionEstudiantes.setText("Estudiantes");
        jGestionEstudiantes.addActionListener(this::jGestionEstudiantesActionPerformed);
        jMenuGestion.add(jGestionEstudiantes);

        jGestionTutores.setText("Tutores");
        jGestionTutores.addActionListener(this::jGestionTutoresActionPerformed);
        jMenuGestion.add(jGestionTutores);

        jGestionMaterias.setText("Materias");
        jMenuGestion.add(jGestionMaterias);

        jMenuBar1.add(jMenuGestion);

        jMenuTutorias.setText("Tutorias");
        jMenuBar1.add(jMenuTutorias);

        jMenuMaterias.setText("Materias");
        jMenuBar1.add(jMenuMaterias);

        jMenuSistema.setText("Sistema");
        jMenuBar1.add(jMenuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionActionPerformed
      
    }//GEN-LAST:event_jMenuGestionActionPerformed

    private void jGestionEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionEstudiantesActionPerformed
        cargarPanel(new panelEstudiante());
    }//GEN-LAST:event_jGestionEstudiantesActionPerformed

    private void jGestionTutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionTutoresActionPerformed
        cargarPanel(new panelGestionTutor());
    }//GEN-LAST:event_jGestionTutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jGestionEstudiantes;
    private javax.swing.JMenuItem jGestionMaterias;
    private javax.swing.JMenuItem jGestionTutores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenu jMenuMaterias;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuTutorias;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
